
[WebSecAcademy What is XXE (XML external entity) injection? Tutorial & Exam…https://d0pt3x.gitbook.io/passion/webapp-security/xxe-attacks/xinclude-attacks](https://d0pt3x.gitbook.io/passion/webapp-security/xxe-attacks/xinclude-attacks)

[https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing](https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing)

https://0xmahmoudjo0.medium.com/exploiting-out-of-band-xxe-in-the-wild-16fc6dad9ee2

https://lab.wallarm.com/xxe-that-can-bypass-waf-protection-98f679452ce0/

https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/XXE%20Injection

https://medium.com/@onehackman/exploiting-xml-external-entity-xxe-injections-b0e3eac388f9

https://www.blackhillsinfosec.com/xml-external-entity-beyond-etcpasswd-fun-profit/

https://web-in-security.blogspot.com/2014/11/detecting-and-exploiting-xxe-in-saml.html

https://web-in-security.blogspot.com/2015/04/on-security-of-saml-based-identity.html

https://www.netspi.com/blog/technical-blog/web-application-pentesting/playing-content-type-xxe-json-endpoints/

https://www.blackhat.com/docs/webcast/11192015-exploiting-xml-entity-vulnerabilities-in-file-parsing-functionality.pdf


Videos

https://www.youtube.com/watch?v=QEMOQE_omg8&list=PL9VLN4DOjAshQVPd7v_pd8i-WqFvMM0yG

https://www.youtube.com/watch?v=1KnRbj6kmsY

https://youtu.be/XwXmRbl7uHA?si=ucEKQ5HYqoPDCbAw

https://youtu.be/2sg9HWGRW-w?si=i1knaSqZuvwNpw2e

https://youtu.be/wWRJwFs_DQc?si=gFDd-vuwpd1Mvngz

https://youtu.be/1KnRbj6kmsY?si=EXP33Mk4QdJeds-b

https://www.youtube.com/watch?v=eBm0YhBrT_c&list=PL9VLN4DOjAshQVPd7v_pd8i-WqFvMM0yG&index=5
